apiVersion: v1
kind: Secret
metadata:
  name: cavalocal-secrets
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgrespassword"
  POSTGRES_DB_BACKEND: "cavalocal"
  POSTGRES_DB_AUDIT: "audit_db"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
  JWT_SECRET: "clave-secreta-desarrollo-cavalocal"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cavalocal-config
  namespace: default
data:
  POSTGRES_BACKEND_HOST: "postgres-backend-service.default.svc.cluster.local"
  POSTGRES_AUDIT_HOST: "postgres-audit-service.default.svc.cluster.local"
  RABBITMQ_HOST: "rabbitmq-service.default.svc.cluster.local"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service.default.svc.cluster.local:5672"
  DATABASE_URL_BACKEND: "postgresql://postgres:postgrespassword@postgres-backend-service.default.svc.cluster.local:5432/cavalocal?schema=public"
  DATABASE_URL_AUDIT: "postgresql://postgres:postgrespassword@postgres-audit-service.default.svc.cluster.local:5432/audit_db?schema=public"
  PORT_BACKEND: "3001"
  PORT_AUDIT: "3002"
  CORS_ORIGINS: "*"
